/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ApiDiffRouteImport } from './routes/api/diff'
import { Route as ApiFileRouteImport } from './routes/api/file'
import { Route as GhSplatRouteImport } from './routes/gh/$'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as ApiAuthRefreshRouteImport } from './routes/api/auth/refresh'
import { Route as ApiAuthSignoutRouteImport } from './routes/api/auth/signout'
import { Route as ApiAuthStartRouteImport } from './routes/api/auth/start'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiffRoute = ApiDiffRouteImport.update({
  id: '/api/diff',
  path: '/api/diff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileRoute = ApiFileRouteImport.update({
  id: '/api/file',
  path: '/api/file',
  getParentRoute: () => rootRouteImport,
} as any)
const GhSplatRoute = GhSplatRouteImport.update({
  id: '/gh/$',
  path: '/gh/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRefreshRoute = ApiAuthRefreshRouteImport.update({
  id: '/api/auth/refresh',
  path: '/api/auth/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignoutRoute = ApiAuthSignoutRouteImport.update({
  id: '/api/auth/signout',
  path: '/api/auth/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthStartRoute = ApiAuthStartRouteImport.update({
  id: '/api/auth/start',
  path: '/api/auth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/setup': typeof SetupRoute
  '/api/diff': typeof ApiDiffRoute
  '/api/file': typeof ApiFileRoute
  '/gh/$': typeof GhSplatRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/auth/start': typeof ApiAuthStartRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/setup': typeof SetupRoute
  '/api/diff': typeof ApiDiffRoute
  '/api/file': typeof ApiFileRoute
  '/gh/$': typeof GhSplatRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/auth/start': typeof ApiAuthStartRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/setup': typeof SetupRoute
  '/api/diff': typeof ApiDiffRoute
  '/api/file': typeof ApiFileRoute
  '/gh/$': typeof GhSplatRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/auth/start': typeof ApiAuthStartRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/setup'
    | '/api/diff'
    | '/api/file'
    | '/gh/$'
    | '/api/auth/callback'
    | '/api/auth/refresh'
    | '/api/auth/signout'
    | '/api/auth/start'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/setup'
    | '/api/diff'
    | '/api/file'
    | '/gh/$'
    | '/api/auth/callback'
    | '/api/auth/refresh'
    | '/api/auth/signout'
    | '/api/auth/start'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/setup'
    | '/api/diff'
    | '/api/file'
    | '/gh/$'
    | '/api/auth/callback'
    | '/api/auth/refresh'
    | '/api/auth/signout'
    | '/api/auth/start'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  SetupRoute: typeof SetupRoute
  ApiDiffRoute: typeof ApiDiffRoute
  ApiFileRoute: typeof ApiFileRoute
  GhSplatRoute: typeof GhSplatRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthRefreshRoute: typeof ApiAuthRefreshRoute
  ApiAuthSignoutRoute: typeof ApiAuthSignoutRoute
  ApiAuthStartRoute: typeof ApiAuthStartRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diff': {
      id: '/api/diff'
      path: '/api/diff'
      fullPath: '/api/diff'
      preLoaderRoute: typeof ApiDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file': {
      id: '/api/file'
      path: '/api/file'
      fullPath: '/api/file'
      preLoaderRoute: typeof ApiFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gh/$': {
      id: '/gh/$'
      path: '/gh/$'
      fullPath: '/gh/$'
      preLoaderRoute: typeof GhSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/refresh': {
      id: '/api/auth/refresh'
      path: '/api/auth/refresh'
      fullPath: '/api/auth/refresh'
      preLoaderRoute: typeof ApiAuthRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signout': {
      id: '/api/auth/signout'
      path: '/api/auth/signout'
      fullPath: '/api/auth/signout'
      preLoaderRoute: typeof ApiAuthSignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/start': {
      id: '/api/auth/start'
      path: '/api/auth/start'
      fullPath: '/api/auth/start'
      preLoaderRoute: typeof ApiAuthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  SetupRoute: SetupRoute,
  ApiDiffRoute: ApiDiffRoute,
  ApiFileRoute: ApiFileRoute,
  GhSplatRoute: GhSplatRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthRefreshRoute: ApiAuthRefreshRoute,
  ApiAuthSignoutRoute: ApiAuthSignoutRoute,
  ApiAuthStartRoute: ApiAuthStartRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
