/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ApiArchiveRouteImport } from './routes/api/archive'
import { Route as ApiDiffRouteImport } from './routes/api/diff'
import { Route as ApiFileRouteImport } from './routes/api/file'
import { Route as GhSplatRouteImport } from './routes/gh/$'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArchiveRoute = ApiArchiveRouteImport.update({
  id: '/api/archive',
  path: '/api/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiffRoute = ApiDiffRouteImport.update({
  id: '/api/diff',
  path: '/api/diff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileRoute = ApiFileRouteImport.update({
  id: '/api/file',
  path: '/api/file',
  getParentRoute: () => rootRouteImport,
} as any)
const GhSplatRoute = GhSplatRouteImport.update({
  id: '/gh/$',
  path: '/gh/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/archive': typeof ApiArchiveRoute
  '/api/diff': typeof ApiDiffRoute
  '/api/file': typeof ApiFileRoute
  '/gh/$': typeof GhSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/archive': typeof ApiArchiveRoute
  '/api/diff': typeof ApiDiffRoute
  '/api/file': typeof ApiFileRoute
  '/gh/$': typeof GhSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/archive': typeof ApiArchiveRoute
  '/api/diff': typeof ApiDiffRoute
  '/api/file': typeof ApiFileRoute
  '/gh/$': typeof GhSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/api/archive'
    | '/api/diff'
    | '/api/file'
    | '/gh/$'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/api/archive'
    | '/api/diff'
    | '/api/file'
    | '/gh/$'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/api/archive'
    | '/api/diff'
    | '/api/file'
    | '/gh/$'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ApiArchiveRoute: typeof ApiArchiveRoute
  ApiDiffRoute: typeof ApiDiffRoute
  ApiFileRoute: typeof ApiFileRoute
  GhSplatRoute: typeof GhSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/archive': {
      id: '/api/archive'
      path: '/api/archive'
      fullPath: '/api/archive'
      preLoaderRoute: typeof ApiArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diff': {
      id: '/api/diff'
      path: '/api/diff'
      fullPath: '/api/diff'
      preLoaderRoute: typeof ApiDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file': {
      id: '/api/file'
      path: '/api/file'
      fullPath: '/api/file'
      preLoaderRoute: typeof ApiFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gh/$': {
      id: '/gh/$'
      path: '/gh/$'
      fullPath: '/gh/$'
      preLoaderRoute: typeof GhSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApiArchiveRoute: ApiArchiveRoute,
  ApiDiffRoute: ApiDiffRoute,
  ApiFileRoute: ApiFileRoute,
  GhSplatRoute: GhSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
