/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ApiCommentsRouteImport } from './routes/api/comments'
import { Route as ApiDiffRouteImport } from './routes/api/diff'
import { Route as GhSplatRouteImport } from './routes/gh/$'
import { Route as ApiGithubPullRouteImport } from './routes/api/github/pull'
import { Route as ApiGithubPullsRouteImport } from './routes/api/github/pulls'
import { Route as ApiGithubViewerRouteImport } from './routes/api/github/viewer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentsRoute = ApiCommentsRouteImport.update({
  id: '/api/comments',
  path: '/api/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiffRoute = ApiDiffRouteImport.update({
  id: '/api/diff',
  path: '/api/diff',
  getParentRoute: () => rootRouteImport,
} as any)
const GhSplatRoute = GhSplatRouteImport.update({
  id: '/gh/$',
  path: '/gh/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubPullRoute = ApiGithubPullRouteImport.update({
  id: '/api/github/pull',
  path: '/api/github/pull',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubPullsRoute = ApiGithubPullsRouteImport.update({
  id: '/api/github/pulls',
  path: '/api/github/pulls',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubViewerRoute = ApiGithubViewerRouteImport.update({
  id: '/api/github/viewer',
  path: '/api/github/viewer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/comments': typeof ApiCommentsRoute
  '/api/diff': typeof ApiDiffRoute
  '/gh/$': typeof GhSplatRoute
  '/api/github/pull': typeof ApiGithubPullRoute
  '/api/github/pulls': typeof ApiGithubPullsRoute
  '/api/github/viewer': typeof ApiGithubViewerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/comments': typeof ApiCommentsRoute
  '/api/diff': typeof ApiDiffRoute
  '/gh/$': typeof GhSplatRoute
  '/api/github/pull': typeof ApiGithubPullRoute
  '/api/github/pulls': typeof ApiGithubPullsRoute
  '/api/github/viewer': typeof ApiGithubViewerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/comments': typeof ApiCommentsRoute
  '/api/diff': typeof ApiDiffRoute
  '/gh/$': typeof GhSplatRoute
  '/api/github/pull': typeof ApiGithubPullRoute
  '/api/github/pulls': typeof ApiGithubPullsRoute
  '/api/github/viewer': typeof ApiGithubViewerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/api/comments'
    | '/api/diff'
    | '/gh/$'
    | '/api/github/pull'
    | '/api/github/pulls'
    | '/api/github/viewer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/api/comments'
    | '/api/diff'
    | '/gh/$'
    | '/api/github/pull'
    | '/api/github/pulls'
    | '/api/github/viewer'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/api/comments'
    | '/api/diff'
    | '/gh/$'
    | '/api/github/pull'
    | '/api/github/pulls'
    | '/api/github/viewer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ApiCommentsRoute: typeof ApiCommentsRoute
  ApiDiffRoute: typeof ApiDiffRoute
  GhSplatRoute: typeof GhSplatRoute
  ApiGithubPullRoute: typeof ApiGithubPullRoute
  ApiGithubPullsRoute: typeof ApiGithubPullsRoute
  ApiGithubViewerRoute: typeof ApiGithubViewerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comments': {
      id: '/api/comments'
      path: '/api/comments'
      fullPath: '/api/comments'
      preLoaderRoute: typeof ApiCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diff': {
      id: '/api/diff'
      path: '/api/diff'
      fullPath: '/api/diff'
      preLoaderRoute: typeof ApiDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gh/$': {
      id: '/gh/$'
      path: '/gh/$'
      fullPath: '/gh/$'
      preLoaderRoute: typeof GhSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/pull': {
      id: '/api/github/pull'
      path: '/api/github/pull'
      fullPath: '/api/github/pull'
      preLoaderRoute: typeof ApiGithubPullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/pulls': {
      id: '/api/github/pulls'
      path: '/api/github/pulls'
      fullPath: '/api/github/pulls'
      preLoaderRoute: typeof ApiGithubPullsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/viewer': {
      id: '/api/github/viewer'
      path: '/api/github/viewer'
      fullPath: '/api/github/viewer'
      preLoaderRoute: typeof ApiGithubViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApiCommentsRoute: ApiCommentsRoute,
  ApiDiffRoute: ApiDiffRoute,
  GhSplatRoute: GhSplatRoute,
  ApiGithubPullRoute: ApiGithubPullRoute,
  ApiGithubPullsRoute: ApiGithubPullsRoute,
  ApiGithubViewerRoute: ApiGithubViewerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
